# Generated by Django 5.2.4 on 2025-08-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], max_length=10),
        ),
    ]
