# Generated by Django 5.2.4 on 2025-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category_alter_postreaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('unlike', 'Unlike'), ('like', 'Like')], max_length=10),
        ),
    ]
