# Generated by Django 5.2.4 on 2025-08-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_is_approved_alter_postreaction_reaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreaction',
            name='reaction_type',
        ),
    ]
